language: ruby

rvm:
  - 2.0.0

before_install:
  - gem --version
  - git submodule update --init --recursive

script:
  - bundle exec fpm-cook --version
  - ls -la
  - bundle exec fpm-cook fpm-cookery/recipes/fpm-cookery/recipe.rb
