language: ruby

rvm:
  - 2.0.0

before_install:
  - gem --version
  - make -f .fpm-cookery.mk before_install

script:
  - bundle exec fpm-cook --version
  - which bundle
  - env | sort
  - sudo PATH=$PATH -E env | sort
  - sudo PATH=$PATH -E make -f .fpm-cookery.mk script
